# Jekyll configuration
language: 'en-us'
markdown: kramdown
highlighter: rouge
paginate: 5

# Website info
name: 'Silviu Rosu'
description: "Let's make programming easier"

# Author's info
author: 'Silviu Rosu'
# edit 'categories' in the front matter of every post to match this username
nickname: silviurosu
bio: 'Pasionate developer specialized in fast web applications with Elixir and OTP, Ruby'
location: 'Iasi, Romania'
url: 'http://www.ubazu.com/'
image: 'assets/images/photo.jpg'

short_url: 'www.ubazu.com'
google_analytics: UA-3062240-2
disqus: silviurosu
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "http://www.ubazu.com/"
# put this in dev
# baseurl: "http://www.ubazu.com/"

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: silviurosu
repo: silviurosu.github.io
branch: master
relative_source: _site
destination: _site
production_url:  http://www.ubazu.com/
source_url:      https://github.com/silviurosu/silviurosu.github.io.git

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
